#!/bin/bash

make
cd bin
if [ -f "acct-database.dat" ]; then rm "acct-database.dat"; fi
if [ -f "input.txt" ]; then rm "input.txt"; fi
if [ -f "output.txt" ]; then rm "output.txt"; fi
if [ -f "cli-output.txt" ]; then rm "cli-output.txt"; fi
cp ../inCollege-Test.txt input.txt
./inCollege | tee -a  cli-output.txt
echo "Here is the diff between cli output and logging: "
diff cli-output.txt output.txt
echo "See bin/output.txt for the autogenerated logs"
cd ..

