name: Run Tests via Bash Script

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t docker-cobol-image .devcontainer/

    - name: Run container (run_tests.sh inside image)
      run: docker run --rm  -v ${{ github.workspace }}:/app -w /app docker-cobol-image /bin/bash -c "chmod 777 run_tests && ./run-tests.sh -b"